### ISSUE TITLE
English translation for the cockpit.

### ISSUE THREAD

**Issue by SP-NTX** [ShFsn/tu154b#20]
While using english pack, most of instruments are not clickable/non functional

**Comment by ShFsn** [comment]
What do you mean? I have an idea what's going on, but I'm not sure.

**Comment by ShFsn** [comment]
And what does this pack contain? To be honest, I never ever saw it.

**Comment by SP-NTX** [comment]
unpacking english_pack.gz overwrites textures and xmls in /Models, but those xmls are not working, they're probably very out-of-dated

**Comment by ShFsn** [comment]
Yes, that is what I thought about. So, I can only recommend you to replace only the textures, manually. They are itself looks to be outdated, but there's no plans to update them because the whole cabin will be reworked from scratch as soon as we will get permission from the authors of the new textures and 3d-model. There will be an english textures included and a'm going to realize a "hot language switch". 

And I can also recommend you to read some manuals in Docs/ folder, at least there are a cabin tour.

**Comment by SP-NTX** [comment]
ofc i replaced textures manually, but it should be fixed to make it easier to add

**Comment by ShFsn** [comment]
I've updated the archive and fixed some most serious mistakes I found in the translation. Installation now should be done just as stated in readme.

**Comment by ShFsn** [comment]
There is a way to change texture files of the model dynamically, so it can be used for "hot" language switch. This will be done after completing #12 and overall translation improvement.
